---
test/language/module-code/instn-resolve-order-src.js:
  module: Expected uncaught exception with name 'ReferenceError' but exception value is not instance of this exception class
test/language/module-code/namespace/internals/define-own-property.js:
  module: 'Exception: Test262Error: Reflect.defineProperty: local1 Expected SameValue(Â«falseÂ», Â«trueÂ») to be true'
test/language/module-code/namespace/internals/object-keys-binding-uninit.js:
  module: 'Exception: Test262Error: Expected a ReferenceError to be thrown but no exception was thrown at all'
test/language/module-code/namespace/internals/set.js:
  module: 'Exception: Test262Error: Reflect.defineProperty: local1 Expected SameValue(Â«falseÂ», Â«trueÂ») to be true'
test/language/module-code/parse-err-hoist-lex-fun.js:
  module: Expected uncaught exception with name 'SyntaxError' but exception value is not instance of this exception class
test/language/module-code/parse-err-reference.js:
  module: Expected uncaught exception with name 'ReferenceError' but exception value is not instance of this exception class
test/language/module-code/privatename-valid-no-earlyerr.js:
  module: "Exception: SyntaxError: Invalid character: '#'"
test/language/module-code/comment-single-line-html-open.js:
  module:
    error: blablabla
test/language/module-code/comment-single-line-html-close.js:
  module:
    error: blablabla
